services:
  - type: web
    runtime: node
    name: sbn
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: "22"
