/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as VoxelRouteImport } from './app/routes/voxel'
import { Route as TopologyRouteImport } from './app/routes/topology'
import { Route as ShapeRouteImport } from './app/routes/shape'
import { Route as SettingsRouteImport } from './app/routes/settings'
import { Route as OptimizationRouteImport } from './app/routes/optimization'
import { Route as MorphologyRouteImport } from './app/routes/morphology'
import { Route as HistoryRouteImport } from './app/routes/history'
import { Route as GeometryRouteImport } from './app/routes/geometry'
import { Route as BacktestRouteImport } from './app/routes/backtest'
import { Route as AnalyticsRouteImport } from './app/routes/analytics'
import { Route as IndexRouteImport } from './app/routes/index'

const VoxelRoute = VoxelRouteImport.update({
  id: '/voxel',
  path: '/voxel',
  getParentRoute: () => rootRouteImport,
} as any)
const TopologyRoute = TopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => rootRouteImport,
} as any)
const ShapeRoute = ShapeRouteImport.update({
  id: '/shape',
  path: '/shape',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizationRoute = OptimizationRouteImport.update({
  id: '/optimization',
  path: '/optimization',
  getParentRoute: () => rootRouteImport,
} as any)
const MorphologyRoute = MorphologyRouteImport.update({
  id: '/morphology',
  path: '/morphology',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GeometryRoute = GeometryRouteImport.update({
  id: '/geometry',
  path: '/geometry',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/backtest': typeof BacktestRoute
  '/geometry': typeof GeometryRoute
  '/history': typeof HistoryRoute
  '/morphology': typeof MorphologyRoute
  '/optimization': typeof OptimizationRoute
  '/settings': typeof SettingsRoute
  '/shape': typeof ShapeRoute
  '/topology': typeof TopologyRoute
  '/voxel': typeof VoxelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/backtest': typeof BacktestRoute
  '/geometry': typeof GeometryRoute
  '/history': typeof HistoryRoute
  '/morphology': typeof MorphologyRoute
  '/optimization': typeof OptimizationRoute
  '/settings': typeof SettingsRoute
  '/shape': typeof ShapeRoute
  '/topology': typeof TopologyRoute
  '/voxel': typeof VoxelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/backtest': typeof BacktestRoute
  '/geometry': typeof GeometryRoute
  '/history': typeof HistoryRoute
  '/morphology': typeof MorphologyRoute
  '/optimization': typeof OptimizationRoute
  '/settings': typeof SettingsRoute
  '/shape': typeof ShapeRoute
  '/topology': typeof TopologyRoute
  '/voxel': typeof VoxelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/backtest'
    | '/geometry'
    | '/history'
    | '/morphology'
    | '/optimization'
    | '/settings'
    | '/shape'
    | '/topology'
    | '/voxel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/backtest'
    | '/geometry'
    | '/history'
    | '/morphology'
    | '/optimization'
    | '/settings'
    | '/shape'
    | '/topology'
    | '/voxel'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/backtest'
    | '/geometry'
    | '/history'
    | '/morphology'
    | '/optimization'
    | '/settings'
    | '/shape'
    | '/topology'
    | '/voxel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BacktestRoute: typeof BacktestRoute
  GeometryRoute: typeof GeometryRoute
  HistoryRoute: typeof HistoryRoute
  MorphologyRoute: typeof MorphologyRoute
  OptimizationRoute: typeof OptimizationRoute
  SettingsRoute: typeof SettingsRoute
  ShapeRoute: typeof ShapeRoute
  TopologyRoute: typeof TopologyRoute
  VoxelRoute: typeof VoxelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voxel': {
      id: '/voxel'
      path: '/voxel'
      fullPath: '/voxel'
      preLoaderRoute: typeof VoxelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topology': {
      id: '/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof TopologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shape': {
      id: '/shape'
      path: '/shape'
      fullPath: '/shape'
      preLoaderRoute: typeof ShapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimization': {
      id: '/optimization'
      path: '/optimization'
      fullPath: '/optimization'
      preLoaderRoute: typeof OptimizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/morphology': {
      id: '/morphology'
      path: '/morphology'
      fullPath: '/morphology'
      preLoaderRoute: typeof MorphologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geometry': {
      id: '/geometry'
      path: '/geometry'
      fullPath: '/geometry'
      preLoaderRoute: typeof GeometryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BacktestRoute: BacktestRoute,
  GeometryRoute: GeometryRoute,
  HistoryRoute: HistoryRoute,
  MorphologyRoute: MorphologyRoute,
  OptimizationRoute: OptimizationRoute,
  SettingsRoute: SettingsRoute,
  ShapeRoute: ShapeRoute,
  TopologyRoute: TopologyRoute,
  VoxelRoute: VoxelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
